package net.unikit.database.internal.implementations;// default package
// Generated 28.10.2015 13:39:49 by Hibernate Tools 4.0.0.Final

import net.unikit.database.internal.interfaces.CourseRegistration;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CourseRegistrationImpl generated by hbm2java
 */
@Entity
@Table(name = "COURSE_REGISTRATION")
final class CourseRegistrationImpl implements CourseRegistration, java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;

    @Column(name = "student_number", nullable = false, length = 31)
	private String studentNumber;

    @Column(name = "course_id", nullable = false)
	private int courseId;

    @Column(name = "currently_assigned_to_team", nullable = false)
	private boolean currentlyAssignedToTeam;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", nullable = false, length = 19)
	private Date createdAt;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_at", nullable = false, length = 19)
	private Date updatedAt;

	public CourseRegistrationImpl() {
	}

	public CourseRegistrationImpl(String studentNumber, int courseId, boolean currentlyAssignedToTeam, Date createdAt,
								  Date updatedAt) {
		this.studentNumber = studentNumber;
		this.courseId = courseId;
		this.currentlyAssignedToTeam = currentlyAssignedToTeam;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getStudentNumber() {
        return studentNumber;
    }

    public void setStudentNumber(String studentNumber) {
        this.studentNumber = studentNumber;
    }

    public int getCourseId() {
        return courseId;
    }

    public void setCourseId(int courseId) {
        this.courseId = courseId;
    }

    public boolean isCurrentlyAssignedToTeam() {
        return currentlyAssignedToTeam;
    }

    public void setCurrentlyAssignedToTeam(boolean currentlyAssignedToTeam) {
        this.currentlyAssignedToTeam = currentlyAssignedToTeam;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CourseRegistrationImpl)) return false;

        CourseRegistrationImpl that = (CourseRegistrationImpl) o;

        return !(getId() != null ? !getId().equals(that.getId()) : that.getId() != null);

    }

    @Override
    public int hashCode() {
        return getId() != null ? getId().hashCode() : 0;
    }

    @Override
    public String toString() {
        return "CourseRegistration{" +
                "id=" + id +
                ", studentNumber='" + studentNumber + '\'' +
                ", courseId=" + courseId +
                ", currentlyAssignedToTeam=" + currentlyAssignedToTeam +
                ", createdAt=" + createdAt +
                ", updatedAt=" + updatedAt +
                '}';
    }
}
