package net.unikit.database.internal.implementations;// default package
// Generated 28.10.2015 13:39:49 by Hibernate Tools 4.0.0.Final

import net.unikit.database.internal.interfaces.Team;
import net.unikit.database.internal.interfaces.TeamInvitation;

import java.util.Date;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TeamInvitationImpl generated by hbm2java
 */
@Entity
@Table(name = "TEAM_INVITATION")
final class TeamInvitationImpl implements TeamInvitation, java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;

    @Column(name = "invitee_student_number", nullable = false, length = 31)
	private String inviteeStudentNumber;

    @ManyToOne
    @JoinColumn(name = "team_id", nullable = false)
	private TeamImpl team;

    @Column(name = "created_by_student_number", nullable = false, length = 31)
	private String createdByStudentNumber;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", nullable = false, length = 19)
	private Date createdAt;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_at", nullable = false, length = 19)
	private Date updatedAt;

	public TeamInvitationImpl() {
	}

	public TeamInvitationImpl(String inviteeStudentNumber, TeamImpl team, String createdByStudentNumber, Date createdAt,
							  Date updatedAt) {
		this.inviteeStudentNumber = inviteeStudentNumber;
		this.team = team;
		this.createdByStudentNumber = createdByStudentNumber;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getInviteeStudentNumber() {
        return inviteeStudentNumber;
    }

    public void setInviteeStudentNumber(String inviteeStudentNumber) {
        this.inviteeStudentNumber = inviteeStudentNumber;
    }

    @Transient
    public Team getTeam() {
        return team;
    }

    @Transient
    public void setTeam(Team team) {
        this.team = (TeamImpl) team;
    }

    public String getCreatedByStudentNumber() {
        return createdByStudentNumber;
    }

    public void setCreatedByStudentNumber(String createdByStudentNumber) {
        this.createdByStudentNumber = createdByStudentNumber;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TeamInvitationImpl)) return false;

        TeamInvitationImpl that = (TeamInvitationImpl) o;

        return !(getId() != null ? !getId().equals(that.getId()) : that.getId() != null);

    }

    @Override
    public int hashCode() {
        return getId() != null ? getId().hashCode() : 0;
    }

    @Override
    public String toString() {
        return "TeamInvitation{" +
                "id=" + id +
                ", inviteeStudentNumber='" + inviteeStudentNumber + '\'' +
                ", createdByStudentNumber='" + createdByStudentNumber + '\'' +
                ", createdAt=" + createdAt +
                ", updatedAt=" + updatedAt +
                '}';
    }
}
