package net.unikit.database.internal.implementations;// default package
// Generated 28.10.2015 13:39:49 by Hibernate Tools 4.0.0.Final

import net.unikit.database.internal.interfaces.Team;
import net.unikit.database.internal.interfaces.TeamRegistration;

import java.util.Date;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TeamRegistrationImpl generated by hbm2java
 */
@Entity
@Table(name = "TEAM_REGISTRATION")
final class TeamRegistrationImpl implements TeamRegistration, java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;

    @Column(name = "student_number", nullable = false, length = 31)
	private String studentNumber;

    @ManyToOne
    @JoinColumn(name = "team_id", nullable = false)
	private TeamImpl team;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", nullable = false, length = 19)
	private Date createdAt;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_at", nullable = false, length = 19)
	private Date updatedAt;

	public TeamRegistrationImpl() {
	}

	public TeamRegistrationImpl(String studentNumber, TeamImpl team, Date createdAt, Date updatedAt) {
		this.studentNumber = studentNumber;
		this.team = team;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getStudentNumber() {
        return studentNumber;
    }

    public void setStudentNumber(String studentNumber) {
        this.studentNumber = studentNumber;
    }

    @Transient
    public Team getTeam() {
        return team;
    }

    @Transient
    public void setTeam(Team team) {
        this.team = (TeamImpl) team;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TeamRegistrationImpl)) return false;

        TeamRegistrationImpl that = (TeamRegistrationImpl) o;

        return !(getId() != null ? !getId().equals(that.getId()) : that.getId() != null);

    }

    @Override
    public int hashCode() {
        return getId() != null ? getId().hashCode() : 0;
    }

    @Override
    public String toString() {
        return "TeamRegistration{" +
                "id=" + id +
                ", studentNumber='" + studentNumber + '\'' +
                ", createdAt=" + createdAt +
                ", updatedAt=" + updatedAt +
                '}';
    }
}
